---

# Lecture 6

---

- [**1. Higher order functions I**](#1.-Higher-order-functions-I)
  - slides 166-172


- [**2. Namespace**](#2.-Namespaces)
  - slides 173 - 178


- [**3. NumPy**](#3.-NumPy)
  - slides 252-277, 320-327
  

---

## 1. Higher order functions I

Functions are [first class objects](http://en.wikipedia.org/wiki/First-class_object) $\leftrightarrow$ functions can be given to other functions as arguments


Motivation:

- Write a function `print_x2_table()` that prints a table of values of $f(x)=x^2$ for $x=0, 0.5, 1.0, .. 2.5$, i.e.

        0.0 0.0
        0.5 0.25
        1.0 1.0
        1.5 2.25
        2.0 4.0
        2.5 6.25


- Then do the same for $f(x)=x^3$.

- Then do the same for $f(x) = \sin(x)$.

In [1]:
def print_x2_table():  # function definition
    for i in range(6):
        x = i * 0.5
        print("{} {}".format(x, x**2))

In [2]:
print_x2_table()       # function call

0.0 0.0
0.5 0.25
1.0 1.0
1.5 2.25
2.0 4.0
2.5 6.25


- We could write separate functions print_x3_table() and print_sin_table() to produce similar tables for functions $x^3$ and $\sin(x)$.

Can we avoid code duplication?

- Idea: Pass function $f(x)$ to tabulate to tabulating fucntion:

In [3]:
def print_f_table(f):  # f is a function
    for i in range(6):
        x = i * 0.5
        print("{}\t{}".format(x, f(x)))

In [4]:
def square(x):         # define function y = x^2
    return x ** 2        # we want to tabulate

In [5]:
print_f_table(square)  # function call

0.0	0.0
0.5	0.25
1.0	1.0
1.5	2.25
2.0	4.0
2.5	6.25


In [6]:
def cubic(x):
    return x ** 3

In [7]:
print_f_table(cubic)  # function call

0.0	0.0
0.5	0.125
1.0	1.0
1.5	3.375
2.0	8.0
2.5	15.625


In [8]:
import math

In [9]:
print_f_table(math.sin)  # function call

0.0	0.0
0.5	0.479425538604203
1.0	0.8414709848078965
1.5	0.9974949866040544
2.0	0.9092974268256817
2.5	0.5984721441039564


Fun example:

In [10]:
funcs = (math.sin, math.cos)

In [11]:
for f in funcs:
    for x in [0, math.pi/2]:
        print("{}({:.3f}) = {:.3f}".format(f.__name__, x, f(x)))

sin(0.000) = 0.000
sin(1.571) = 1.000
cos(0.000) = 1.000
cos(1.571) = 0.000


---

## 2. Namespaces



We distinguish between

- _global_ variables (defined in main program)
- _local_ variables (defined for example in functions)
- _built-in_ functions


- Note that imported modules have their own name space.

The same variable can be used in a function and in the main program but they can refer to different objects and do not interfere:

In [12]:
def f():  # f() does not return value, only prints
    x = 'I am local'
    print(x)

In [13]:
x = 'I am global'

In [14]:
f()

I am local


In [15]:
print(x)

I am global


- So global and local variables can't see each other? Not quite, if -- within a function -- we try to access an object through its name, then Python will look for this name:
    
    - First in the local name space (i.e. within that function)
    - Then in the global name space
    - If the variable can not be found, then a `NameError` is raised.
 
 
- This means, we can _read_ global variables from functions.

Example:

In [16]:
def f():   # f() does not return value, only prints
    print(x)

In [17]:
x = 'I am global'

In [18]:
f()

I am global


- But local variables "shadow" global variables

In [19]:
def f():
    y = 'I am local y'
    print(x)
    print(y)

In [20]:
x = 'I am global x'
y = 'I am global y'

In [21]:
f()

I am global x
I am local y


In [22]:
print("back in main:")
print(y)

back in main:
I am global y


- To `modify` global variables within a local namespace, we need to use the `global` keyword


- Generally, the use of global variables is not recommended:

    - Functions should take all necessary input as arguments and return all relevant output.
    - This makes the functions work as independent modules which is good engineering practice and essential to control complexity of software.


- However, the use of global variables may be suitable when the same constant or variable (such as the mass of an object) is required throughout a program:

    - Because it is not good practice to define this variable more than once (it is likely that we assign different values and get inconsistent results)
    - In this case -- in small programs -- the use of (read-only) global variables may be acceptable.
    - Object Oriented Programming provides a somewhat neater solution to this.

### 2.1. Python's look up rule

- When coming across an identifier, Python looks for this in the following order in

    - the local name space (L)

    - if appropriate in the next higher level local name space), (L$^2$, L$^3$, $\ldots$)

    - the global name space (G)
    
    - the set of built-in commands (B)


- This is summarised as LGB or L$^n$GB.


- If the identifier cannot be found, a `NameError` is raised.

---

## 3. NumPy


- NumPy is an interface to high performance linear algebra libraries (ATLAS, LAPACK, BLAS).


- It provides:

    - the `array` object
    - fast mathematical operations over arrays
    - linear algebra, Fourier transforms, Random Number generation


- An `array` is a sequence of objects.


- All objects in one `array` are of the same type.


- NumPy is _not_ part of the Python standard library (import as a module).




### 3.1. Basic concepts

In [23]:
import numpy as np

In [24]:
a = np.array([1, 4, 10])  # 1D array object

In [25]:
type(a)

numpy.ndarray

In [26]:
a

array([ 1,  4, 10])

In [27]:
print(a)

[ 1  4 10]


In [28]:
B = np.array([[0, 1.5], [10, 12]])  # 2D array (matrix)

In [29]:
type(B)

numpy.ndarray

In [30]:
B

array([[ 0. ,  1.5],
       [10. , 12. ]])

In [31]:
print(B)

[[ 0.   1.5]
 [10.  12. ]]


- NumPy arrays can be defined by convering lists to arrays by using `array` conversion, as we have done above. We can also convert tuples to arrays:

In [32]:
t = (1, 3, 4, 5, 6, 10, 1, 4, 10)  # tuple

a = np.array(t)  # convert to array

a

array([ 1,  3,  4,  5,  6, 10,  1,  4, 10])

- Other useful methods are NumPy's `zeros` and `ones` which accept a desired matrix shape as the input:

In [33]:
B = np.zeros((3, 4))  # function zeros takes a tuple as input

B

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [34]:
C = np.ones((4, 2))  # function ones takes a tuple as input

In [35]:
C

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [36]:
a.shape  # shape of an array retuned as a tuple

(9,)

In [37]:
B.shape

(3, 4)

In [38]:
C.shape

(4, 2)

- All elements in an array must be of the same type. For existing array, the type is the `dtype` attribute:

In [39]:
a.dtype

dtype('int64')

In [40]:
B.dtype

dtype('float64')

__Indexing and slicing__

In [41]:
a

array([ 1,  3,  4,  5,  6, 10,  1,  4, 10])

In [42]:
a[:4]  # all elements up to and excluding the 4th element

array([1, 3, 4, 5])

In [43]:
a[-1]  # last element

10

In [44]:
a[3:7]  # all elements between the 3rd (included)
        # and 7th (excluded) element

array([ 5,  6, 10,  1])

In [45]:
a[3:7:2]  # slicing with a step (2 in this case)

array([ 5, 10])

In [46]:
a[3:7:-1]  # slicing with reversed stepping

array([], dtype=int64)

In [47]:
a[7:3:-1]

array([ 4,  1, 10,  6])

In [48]:
a

array([ 1,  3,  4,  5,  6, 10,  1,  4, 10])

In [49]:
a[::-1]  # reversing an array

array([10,  4,  1, 10,  6,  5,  4,  3,  1])

In [50]:
B

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [51]:
B[2, 3]

0.0

In [52]:
B[-1, -1]

0.0

In [53]:
B[:, 1]   # column with index 1

array([0., 0., 0.])

In [54]:
B[0, :]  # row with index 0

array([0., 0., 0., 0.])

### 3.2. Why is NumPy useful



- NumPy arrays allow element-wise evaluation of mathematical functions over entire array. 

In [55]:
a

array([ 1,  3,  4,  5,  6, 10,  1,  4, 10])

In [56]:
a**2   # Element-wise second power

array([  1,   9,  16,  25,  36, 100,   1,  16, 100])

In [57]:
np.sqrt(a)  # element-wise square root

array([1.        , 1.73205081, 2.        , 2.23606798, 2.44948974,
       3.16227766, 1.        , 2.        , 3.16227766])

In [58]:
np.sin(a)

array([ 0.84147098,  0.14112001, -0.7568025 , -0.95892427, -0.2794155 ,
       -0.54402111,  0.84147098, -0.7568025 , -0.54402111])

In [59]:
a > 3

array([False, False,  True,  True,  True,  True, False,  True,  True])

- Compare with `math.sqrt` which operates only on a single element:

In [60]:
import math as m

m.sqrt(2)  # allows only single element input

1.4142135623730951

In [61]:
m.sin(2)

0.9092974268256817

To imitate `NumPy`-like operations using `math` module, we could implement, for example, the square root over elements of a sequence of numbers as:

In [62]:
t  # tuple of integers defined above

(1, 3, 4, 5, 6, 10, 1, 4, 10)

In [63]:
lsqrt = []   # initialis the final list that will contain square roots

for i in t:
    lsqrt.append(m.sqrt(i))  # calculate square root of individual elements
                             # and append to a new list

tsqrt = tuple(lsqrt)  # convert to tuple

print(lsqrt)

[1.0, 1.7320508075688772, 2.0, 2.23606797749979, 2.449489742783178, 3.1622776601683795, 1.0, 2.0, 3.1622776601683795]


__Additional comments__

- NumPy provides broad range of linear algebra tools, for example: <br><br>

    - `pinv` to compute the inverse of a matrix

    - `svd` to compute a singular value decomposition

    - `det` to compute the determinant

    - `eig` to compute eigenvalues and eigenvectors


- Use `help(numpy.linalg)` for an overview.


- NumPy will be used extensively in the following lectures.

### 3.3. Summary of sequences

- arrays, similarly to lists, strings and tuples are sequences.


- sequences share the following operations


        a[i]      returns i-th element of a
        a[i:j]    returns elements i up to j-1  
        len(a)    returns number of elements in sequence
        min(a)    returns smallest value in sequence
        max(a)    returns largest value in sequence
        x in a    returns True if x is element in a
        a + b     concatenates a and b
        n * a     creates n copies of sequence a
        
- In this table _a_, _b_ are sequences, _i_, _j_, _n_ are integers

---